stages:
  - lint
  - deploy

codespell:
  stage: lint
  image: "docker.io/bilelmoussaoui/codespell"
  script:
    - codespell -S "*.png,*.po,.git,*.jpg" -f

pages:
  stage: deploy
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  only:
    - main
  artifacts:
    paths:
      - public
  cache:
    paths:
      - $CARGO_HOME/bin
