stages:
  - lint
  - test
  - deploy

codespell:
  stage: lint
  image: "docker.io/bilelmoussaoui/codespell"
  script:
    - codespell -S "*.png,*.po,.git,*.jpg" -f

doctests:
  stage: test
  image: "docker.io/bilelmoussaoui/gtk4"
  before_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
    - source $HOME/.cargo/env
  script:
    - cd tests
    - xvfb-run -a -s "-screen 0 1024x768x24" cargo test

pages:
  stage: deploy
  image: rust:latest
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - mdbook --version || cargo install mdbook
  script:
    - mdbook build -d public
  only:
    - main
  artifacts:
    paths:
      - public
  cache:
    paths:
      - $CARGO_HOME/bin
